### PR TITLE
Deprecate repo ignoregroups

### PR DESCRIPTION
**Pull request by jkonecny12**
The ``repo --ignoregroups`` parameter is not used by Anaconda from yum -> dnf transition. I don't think we want to add it back but instead we can remove this from our API.

P.S.: Not sure if the deprecation is done correctly. Could you please verify that before merge @bcl.

### CODE REVIEW

**Comment by bcl** [comment]
I've added some fixes as a fixup commit, squash it with the previous one if you like them.

**Comment by jkonecny12** [comment]
Thanks a lot for your fixes.

**Comment by jkonecny12** [comment]
Could this be merged or do we waiting for something?

**Comment by bcl** [comment]
I was waiting for you to squash my fixup commit with yours :)

**Comment by jkonecny12** [comment]
Squashed! Sorry it took me so long.

**Pull request merged**
