### PR TITLE
Port DNS handling to RHEL 9

### PR DESCRIPTION
**Pull request by VladimirSlavik**
This adds four new options to control handling of DNS:

--ipv4-dns-search
--ipv6-dns-search
--ipv4-ignore-auto-dns
--ipv6-ignore-auto-dns

Related: [rhbz#2065754](https://bugzilla.redhat.com/show_bug.cgi?id=2065754)

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
Do I need a pykickstart bug on RHEL for this, or is `Related:` for an anaconda one enough?

**Comment by VladimirSlavik** [comment]
Ouch, maybe the branch needs also #432?

**Comment by VladimirSlavik** [comment]
The bug is for 9.3 and needs acks, otherwise this seems to be fine.

**Review by bcl — APPROVED** [review]
Ack!

**Pull request merged**
