### PR TITLE
Remove the multipath command

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Deprecated since F24.

### CODE REVIEW

**Review by poncovka — COMMENTED** [review]
Looks good to me. Thanks!

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Review by bcl — CHANGES_REQUESTED** [review]
Please refactor to use RemovedCommand now that it's merged.

**Comment by VladimirSlavik** [comment]
Blocked by #366 test fix

**Review by bcl — APPROVED** [review]
Thanks!

**Pull request merged**
