### PR TITLE
Remove the device command

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Deprecated since F24

edit: Blocked by #366

### CODE REVIEW

**Review by poncovka — COMMENTED** [review]
Looks good to me.

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Review by bcl — CHANGES_REQUESTED** [review]
Please refactor to use RemovedCommand now that it's merged.

**Comment by VladimirSlavik** [comment]
Thanks for the nudge, fixed.

**Comment by VladimirSlavik** [comment]
On a second thought, let's have the fix independently in #366, and leave this blocked by that one.

**Review by bcl — APPROVED** [review]
Thanks!

**Pull request merged**
