### PR TITLE
Remove the install command

### PR DESCRIPTION
**Pull request by VladimirSlavik**
~~At the moment still blocked by deployment of Beaker 28.1. See #347 for more details.~~

### CODE REVIEW

**Comment by jstodola** [comment]
Beaker 28.1 has been deployed, so it's not blocking merging of this change.
The install command is still used in the kickstart-tests, PR to remove it from there: https://github.com/rhinstaller/kickstart-tests/pull/455

**Review by poncovka — COMMENTED** [review]
Looks good to me. Thanks!

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by bcl** [comment]
Thanks for keeping track of this!

**Pull request merged**
