### PR TITLE
Remove install & deviceprobe commands

### PR DESCRIPTION
**Pull request by VladimirSlavik**
They have been deprecated for quite a long time - since F29.

### CODE REVIEW

**Review by poncovka — COMMENTED** [review]
Looks good to me. Thanks!

**Comment by jstodola** [comment]
Can you please wait a bit before merging this PR? Although the install command has been deprecated for a while, this change would cause problems for installations via Beaker (https://beaker-project.org/), where the install command is still provided in the kickstart file even for rawhide.

**Comment by jkonecny12** [comment]
Thanks @jstodola for keeping an eye on these!

**Comment by StykMartin** [comment]
Changes for Beaker are merged. Hard to say when they will release it 🤔

**Comment by StykMartin** [comment]
Beaker 28.1 released. This version contains a fix for `install` ks command.

**Comment by VladimirSlavik** [comment]
Does released also mean deployed?

**Comment by StykMartin** [comment]
> Does released also mean deployed?

Released means the upstream release and I believe it is available downstream as well.
However, for deployment, I would urge on `beaker-dev-list@redhat.com`.

I can't perform deployments as I'm not part of RH anymore. But the deployment of this is a manner of minutes afaik.

**Comment by VladimirSlavik** [comment]
So, "install" is still blocked, and the deviceprobe part is not. I think I'll split that to another PR.

**Comment by VladimirSlavik** [comment]
Needs changing to use `RemovedCommand`.

**Comment by VladimirSlavik** [comment]
Deviceprobe split off into #367.

**Comment by VladimirSlavik** [comment]
Closing since this was split into PRs #367 and #368.

**Pull request closed without merging**
